import SidebarComponent from "components/Sidebar";
import "../styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isLogged = true;

  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={"dark"}>
        {isLogged && <SidebarComponent></SidebarComponent>}
        {children}
      </body>
    </html>
  );
}
