import SidebarComponent from "components/Sidebar";
import "../styles/globals.css";
import { Inter } from "next/font/google";
import Login from "./user/login/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isLogged = true;

  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={"dark flex  items-center justify-center"}>
        {isLogged ? (
          <div className="w-[350px]">
            <SidebarComponent /> {children}
          </div>
        ) : (
          <div className="w-[350px] ">
            <Login />
          </div>
        )}
      </body>
    </html>
  );
}
